steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'engines/melee/server/Dockerfile', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
